# Generated by Django 2.0.6 on 2018-06-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cas_no', models.CharField(max_length=32)),
                ('molecular_ormula', models.CharField(max_length=32)),
                ('molecular_weight', models.FloatField()),
                ('molecular_structure', models.CharField(max_length=128)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yieldpharm1.Category')),
            ],
        ),
    ]
